#!/usr/bin/perl
# no -d allowed when running suid from the cgi-bin dir :-(
#-wT
# vim: ft=xml:

#----------------------------------------------------------------------
# heading     : Configuration
# description : E-mail WBL
# navigation  : 6000 6710
#----------------------------------------------------------------------

use strict;
use warnings;
use Mojolicious::Lite;
use smeserver::Panel::wblNew;


# We can use separate template in templates/somefile.html.ep
# plugin 'HTMLTemplateProRenderer';

# Load up our wbl subroutines
# my $f = esmith::wblNew->new();

# Initial setup when called
get '/' => sub {

    my ($mojo) = @_;

    # Setup our 3  - test
    # $mojo->stash( RBL => 'RBL List', Black => 'Black List', White => 'White List' );

    # Or use a dropdown list
    my @wblList = ( 'RBL List', 'Black List', 'White List' );
    $mojo->stash( list => \@wblList );

    # This is the template fragment to be embedded in main
    $mojo->stash( contentVar => '_choice' );

    # And now we render main
    $mojo->render( template => 'main' );

};

#get 'test1' => sub {
#};

#get 'test2' => sub {
#};

# called via post
post '/' => sub {

    # push the returned array to the $mojo array
    my $mojo = shift;

    my $button = $mojo->param('button');

    # This is the name used in the select_files e.g. 'list'
    my $list = $mojo->param('list');

    # We should put the vars below into these SWITCH statements
    # We can then check the call in the $list var.
    # If it is a straightforward POST call we return a template
    # If it is like wbl.cgi?get_dnsbl or wbl.cgi?get_rblSettings or similar
    # we could return some JSON instead
    # Just needs some logic to figure the call style and output relevant data

    # Hmm some of this comes back as a carriage return separated array
    # For now removed the \n and join in the wbl.pm file
    # eg joe@domain.com\nfred@domain.com
    #

    SWITCH: {

        if ( $list =~ /^RBL List/ ) {

            # Set the template we require
            # You could do some logic to either call a template to output the data,
            # or alternatively answer a query with some JSON instead
            $mojo->stash( contentVar => '_rbl' );

            # Set the retrieved list name to display it for testing
            $mojo->stash( listR => $list );

            # For RBL List
            # dnsbl - returns 'enabled/disabled
            my $dnsbl = get_dnsbl();
            $mojo->stash( dnsbl => $dnsbl );

            # rhsbl - returns 'enabled/disabled
            my $rhsbl = get_rhsbl();
            $mojo->stash( rhsbl => $rhsbl );

            # uribl - returns 'enabled/disabled
            my $uribl = get_uribl();
            $mojo->stash( uribl => $uribl );

            # For SBLList List
            my @sbllist = get_sbllist();
            $mojo->stash( sbllist => \@sbllist );

            # For RBLList List
            my @rbllist = get_rbllist();
            $mojo->stash( rbllist => \@rbllist );

            # For URLList List
            my @ubllist = get_ubllist();
            $mojo->stash( ubllist => \@ubllist );

        }
        if ( $list =~ /^Black List/ ) {

            # Set the template we require
            # You could do some logic to either call a template to output the data,
            # or alternatively answer a query with some JSON instead
            $mojo->stash( contentVar => '_black' );

            # Set the retrieved list name to display it for testing
            $mojo->stash( listR => $list );

            # For Black List
            my @badhelo = get_badhelo();
            $mojo->stash( badhelo => \@badhelo );

            my @badmailfrom = get_badmailfrom();
            $mojo->stash( badmailfrom => \@badmailfrom );

        }
        if ( $list =~ /^White List/ ) {

            # Set the template we require
            # You could do some logic to either call a template to output the data,
            # or alternatively answer a query with some JSON instead
            $mojo->stash( contentVar => '_white' );

            # Set the retrieved list name to display it for testing
            $mojo->stash( listR => $list );

            # For WBL List
            my @whitelistsenders = get_whitelistsenders();
            $mojo->stash( whitesenders => \@whitelistsenders );

            my @whitelisthelo = get_whitelisthelo();
            $mojo->stash( whitehelo => \@whitelisthelo );

            my @whitelisthosts = get_whitelisthosts();
            $mojo->stash( whitehosts => \@whitelisthosts );

            my @whitelistfrom = get_whitelistfrom();
            $mojo->stash( whitefrom => \@whitelistfrom );

        }

        # Fall through back to choice list
        # Not sure how do do an 'else' though !
        #        my @wblList = ( 'RBL List', 'Black List', 'White List' );
        #        $mojo->stash( list       => \@wblList );
        #        $mojo->stash( contentVar => '_choice' );
    }

    $mojo->render( template => 'main' );
};

app->start;

